import AsyncStorage from '@react-native-async-storage/async-storage';

/**
 * The two identifiers that make a report answerable.
 *
 * Every event and every crash already carried a version and a variant, and
 * nothing tied them together: an operator looking at a crash could not find the
 * five events that led to it, and could not tell one reader hitting a bug
 * thirty times from thirty readers hitting it once.
 *
 * Two ids, both random and both deliberately *not* the uid:
 *
 *  - **session** — one app launch. This is the correlation key: the crash and
 *    the events around it share it.
 *  - **install** — this installation of the app, across launches. It answers
 *    "one device or many", which is the difference between a crash worth
 *    stopping a release for and one that is not.
 *
 * Neither identifies a person. The install id is regenerated by a reinstall and
 * is destroyed with the rest of the device's data on account deletion, so it
 * cannot outlive what it describes.
 */

export const INSTALL_ID_KEY = 'dananeh.telemetry.installId';

/** Hex from `crypto.getRandomValues`, falling back to `Math.random`. */
function randomId(bytes = 8): string {
  const buffer = new Uint8Array(bytes);

  const source = (globalThis as { crypto?: Crypto }).crypto;
  if (source?.getRandomValues) source.getRandomValues(buffer);
  else for (let index = 0; index < bytes; index += 1) buffer[index] = Math.floor(Math.random() * 256);

  return Array.from(buffer, (byte) => byte.toString(16).padStart(2, '0')).join('');
}

/**
 * One launch. Generated eagerly so an event recorded before storage is ready —
 * a crash during startup, the case most worth having — still correlates.
 */
const session = randomId();

export const sessionId = (): string => session;

let install: string | null = null;

export async function installId(): Promise<string> {
  if (install) return install;

  try {
    const stored = await AsyncStorage.getItem(INSTALL_ID_KEY);
    if (stored) {
      install = stored;
      return install;
    }

    const created = randomId(8);
    await AsyncStorage.setItem(INSTALL_ID_KEY, created);
    install = created;
    return install;
  } catch {
    // Storage refused — a private-mode browser, a full disk. A per-session id
    // is still better than none; it just cannot answer "one device or many".
    install = session;
    return install;
  }
}

/** Used by tests, and by the wipe that follows account deletion. */
export function __resetCorrelation() {
  install = null;
}
